services:
  - type: web
    name: credito-bancolombia
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    rootDir: .
    numInstances: 1
    autoDeploy: yes
    pullRequestPreviewsEnabled: no
    healthCheckPath: /
    ipAllowList:
      - cidrBlock: 0.0.0.0/0
        description: everywhere
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: DB_HOST
        value: 2.25.79.121
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: u423799403_eldemon777
      - key: DB_USER
        value: u423799403_eldemon777
      - key: DB_PASS
        value: "777Eldemon"
